baseurl = "https://podlesi-fest.cz"
#baseurl = "http://localhost:1313/"
languageCode = "cs"
title = "Podlesí Fest"
theme = "pld-theme"
googleAnalytics = "UA-174451951-1"
publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Podlesí Fest"

		[params.navigation.links]
      interprets  = "Interpreti"
			program 	 	= "Na co se těšit"
			location		= "Jak k nám"
			tickets			= "Vstupenky"
			star     	= "Chci vystupovat"

		[params.navigation.socials]
			[[params.navigation.socials.list]]
				icon = "facebook"
				link = "https://www.facebook.com/events/1029688561522209"

			[[params.navigation.socials.list]]
				icon = "instagram"
				link = "https://www.instagram.com/podlesi_fest/"


	# intro section
	[params.intro]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Podlesí Fest"

	# About section
	[params.star]
		headline    = "Chci vystupovat"
		description = "Chtěl by si festovně zakalit, ale taky zahrát? Není problém. Napiš nám něco o sobě a nějak už se domluvíme. Případně nás můžeš kontaktovat přes facebook, nebo rovnou zavolat."
		phone 			= "+420 608 055 822"
		email 			= "party@podlesi-fest.cz"

	# Service section
	[params.interprets]
		headline = "Letos vystoupí"

			[[params.interprets.list]]
				icon = "shorfitsch"
				link = "https://soundcloud.com/ond-ej-orfa?fbclid=IwAR3G1s0lOMh8M2L4A9ZxHPJPybKcp9nsQv4q0L_c739A_mpjAEQhy9wIaBA"
				title = "Shor Fitsch"
				description = "Live improvised electronic dance&nbsp;music"

			[[params.interprets.list]]
				icon = "vaasha"
				title = "Vaasha"
				link = "https://www.mixcloud.com/vaasha/?fbclid=IwAR03bk0CnI9956V1RKRttYoiC9Fqzui1KHYtuv9iEVdIiKZpExxTyDZMX6g"
				description = "Deep techno, house"

			#[[params.interprets.list]]
			#	icon = "konrads"
			#	link = "https://soundcloud.com/konrad0"
			#	title = "Konrad S."
			#	description = "Synth jams"

			[[params.interprets.list]]
				icon = "harry"
				link = "https://open.spotify.com/playlist/4X8JDu3V3P7udw4WvoouMs?si=LTGhMDvoSVOclzqzG6tYZA"
				title = "Harry von Königgrätz"
				description = "House dance music"

			[[params.interprets.list]]
				icon = "kostik"
				link = "https://www.youtube.com/watch?v=K5vLNRCIF0k"
				title = "Костик"
				description = "Dubstep, Drum & Bass, club"

		    #[[params.interprets.list]]
        		#  icon = "youtube"
				#	link = "https://www.youtube.com/watch?v=oaYteZ8QJsc&t=315s"
        		#  title = "DJ YouTube"
        		#  description = "Interpret, který nesmí chybět na žádné párty!"

			#[[params.interprets.list]]
			#	icon = "you"
			#	link = "https://www.youtube.com/watch?v=FrEP4MHCKDc&list=RDMM&start_radio=1&rv=oaYteZ8QJsc"
			#	title = "Právě ty"
			#	description = "Zúčastni se jam session"

    # program modals
	[params.program.modal]
  	buttonText = "Zavřít"

	# Google Maps section
	 [params.location]
	 	headline = "Jak se k nám dostanete"
		description = "YOu you"
	 	latitude  = "50.267853"
	 	longitude = "12.882203"
	 	maps_api_key = "AIzaSyADDvRS1ctmnFAaXxgJ_cB4DZebsxLKg-8"

	# Tickets
	[params.tickets]
		headline = "Vstupenky"
		phone = "+420 608 055 822"
		email = "party@podlesi-fest.cz"

		[[params.tickets.paras]]
			para = "Letošní ročník je vstupné zcela dobrovolné. Rozhodně se však na tebe nebudeme zlobit, když nám i tak nějaký ten fufník přispěješ, abychom mohli vše bez problémů zařídit a ty sis si mohl/a Podlesí řádně užít, jak se sluší a patří. <br>⌐■_■"

		[[params.tickets.paras]]
			para = "Neboj, vše dáváme do Podlesí. Ani koruna nepadne na učebnice, dětský sirotčinec, či boj proti malárii. Doporučená výše vstupného na 2 dny je <strong>350 kč</strong>. Samozřejmě se však nebudeme zlobit ani za klíčky od auta, či zámek po babičce ;)"
