#baseurl = "https://podlesi-fest.cz"
baseurl = "http://localhost:1313/"
languageCode = "cs"
title = "Podlesí Fest"
theme = "pld-theme"
publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# Define id for google analytics
	googleAnalytics = "UA-174451951-1"

	# The path must be relative to the static folder
	favicon = "favicon.ico"
	
	# switch theme variant
	theme_dark_variant = true

	# Navigation
	[params.navigation]
		brand = "Podlesí Fest"

		[params.navigation.links]
      interprets  = "Interpreti"
			program 	 	= "Na co se těšit"
			location		= "Jak k nám"
			tickets			= "Vstupenky"
			star     	= "Chci vystupovat"

		[params.navigation.socials]
			[[params.navigation.socials.list]]
				icon = "facebook"
				link = "https://www.facebook.com/groups/562104477769013"

			[[params.navigation.socials.list]]
				icon = "instagram"
				link = "https://www.instagram.com/podlesi_fest/"


	# intro section
	[params.intro]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Podlesí Fest"
		date = "25-27.7"
		unix_timestam_counter = "1753466400000"


	# About section
	[params.star]
		headline    = "Chci vystupovat"
		description = "Chtěl by si festovně zakalit, ale taky zahrát? Není problém. Napiš nám něco o sobě a nějak už se domluvíme. Případně nás můžeš kontaktovat přes facebook, nebo rovnou zavolat."
		phone 			= "+420 608 055 822"
		email 			= "party@podlesi-fest.cz"

	# Service section
	[params.interprets]
		headline = "Letos vystoupí"
		display_lineup = false

			[[params.interprets.list]]
				icon = "shorfitsch"
				link = "https://soundcloud.com/ond-ej-orfa?fbclid=IwAR3G1s0lOMh8M2L4A9ZxHPJPybKcp9nsQv4q0L_c739A_mpjAEQhy9wIaBA"
				title = "Shor Fitsch"
				description = "Tropical techno"

			[[params.interprets.list]]
				icon = "vaasha"
				title = "Vaasha"
				link = "https://www.mixcloud.com/vaasha/?fbclid=IwAR03bk0CnI9956V1RKRttYoiC9Fqzui1KHYtuv9iEVdIiKZpExxTyDZMX6g"
				description = "Techno"

			#[[params.interprets.list]]
			#	icon = "konrads"
			#	link = "https://soundcloud.com/konrad0"
			#	title = "Konrad S."
			#	description = "Synth jams"

			[[params.interprets.list]]
				icon = "harry"
				link = "https://open.spotify.com/playlist/4X8JDu3V3P7udw4WvoouMs?si=LTGhMDvoSVOclzqzG6tYZA"
				title = "Harry von Königgrätz"
				description = "Popping, Hip Hop, Dance, House"

			[[params.interprets.list]]
				icon = "kostik"
				link = "https://www.youtube.com/watch?v=K5vLNRCIF0k"
				title = "Костик"
				description = "Dubstep, Drum & Bass, club"

		    #[[params.interprets.list]]
        	#	icon = "cry.nn"
			#	link = "https://soundcloud.com/crydotnn"
        	#	title = "CRY.NN"
        	#	description = "Techno"

			#[[params.interprets.list]]
			#	icon = "bigmama"
			#	link = "#"
			#	title = "BIGMAMA"
			#	description = "dnb"

    # program modals
	[params.program.modal]
  	buttonText = "Zavřít"

	# Google Maps section
	 [params.location]
	 	headline = "Jak se k nám dostanete"
		description = "YOu you"
	 	latitude  = "50.267853"
	 	longitude = "12.882203"
	 	maps_api_key = "AIzaSyADDvRS1ctmnFAaXxgJ_cB4DZebsxLKg-8"

	# Tickets
	[params.tickets]
		headline = "Vstupenky"
		phone = "+420 608 055 822"
		email = "party@podlesi-fest.cz"

		[[params.tickets.paras]]
			para = "Letošní ročník je vstupné opět dobrovolné. Rozhodně se však na tebe nebudeme zlobit, když nám i tak něco málo přispěješ. Doporučená výše vstupného na 2 dny je <strong>350 kč</strong>. Za ně dostaneš přístup k pípě po celou dobu akce, slušivou pásku a lehký tematický doplněk."

		[[params.tickets.paras]]
			para = "Pokud se nás rozhodneš podpořit částkou <strong>450+</strong>. Odměnou ti bude navíc ještě lepší karma a vzácný ještěří artefakt."