baseurl = "https://ikinik.github.io/podlesi-fest/"
languageCode = "cs"
title = "Podlesí Fest"
theme = "pld-theme"
googleAnalytics = ""
publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Podlesí Fest"

		[params.navigation.links]
      services  = "Interpreti"
			portfolio = "Na co se těšit"
			location	= "Jak k nám"
			tickets		= "Vstupenky"
			about     = "Chci vystupovat"

		[params.navigation.socials]
			[[params.navigation.socials.list]]
				icon = "facebook"
				link = "https://www.facebook.com/groups/562104477769013/"

			[[params.navigation.socials.list]]
				icon = "instagram"
				link = "https://www.instagram.com/?hl=cs#reactivated"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Podlesí Fest"

	# About section
	[params.about]
		headline    = "Chci vystupovat"
		#description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		description = "Chtěl by si festovně zakalit, ale taky zahrát? Není problém. Napiš nám něco o sobě a nějak už se domluvíme. Případně nás můžeš kontaktovat přes facebook, nebo rovnou zavolat."
		phone 			= "+420 608 055 822"
		email 			= "kontakt@podlesi-fest.cz"

	# Service section
	[params.services]
		headline = "Letos vystoupí"

        [[params.services.list]]
            icon = "shorfitsch"
						link = "https://soundcloud.com/ond-ej-orfa?fbclid=IwAR3G1s0lOMh8M2L4A9ZxHPJPybKcp9nsQv4q0L_c739A_mpjAEQhy9wIaBA"
            title = "Shor Fitsch"
            description = "Live improvised electronic dance&nbsp;music"

        [[params.services.list]]
      			icon = "vasa"
      			title = "Váša"
						link = "https://www.mixcloud.com/vaasha/?fbclid=IwAR03bk0CnI9956V1RKRttYoiC9Fqzui1KHYtuv9iEVdIiKZpExxTyDZMX6g"
      			description = "Deep techno, house"

				[[params.services.list]]
	    			icon = "lamind"
						link = "https://www.instagram.com/la_mind_band/?fbclid=IwAR3QGcR8N8OpDsY-FeNaYT0JorS-3G7tEt9adrz4z0DcLRdS5OJAlMprg6o"
	    			title = "La Mind"
	    			description = "Folk, Dream pop, Shoegaze, Rock"

		    [[params.services.list]]
            icon = "youtube"
						link = "https://www.youtube.com/watch?v=oaYteZ8QJsc&t=315s"
            title = "DJ YouTube"
            description = "Interpret, který nesmí chybět na žádné párty!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		facebook = "123-456-6789"
		instagram = "feedback@startbootstrap.com"

	# Google Maps section
	 [params.location]
	 	headline = "Jak se k nám dostanete"
		description = "YOu you"
	 	latitude  = "50.267853"
	 	longitude = "12.882203"
	 	maps_api_key = "AIzaSyADDvRS1ctmnFAaXxgJ_cB4DZebsxLKg-8"

	# Tickets
	[params.tickets]
		headline = "Vstupenky"
		phone = "+420 608 055 822"
		email = "kontakt@podlesi-fest.cz"

		[[params.tickets.paras]]
			para = "Vstupenky můžeš koupit v předprodeji. Budeme moc rádi když nám zavčasu přispěješ, abychom moli bez problémů vše zařídit a ty sis mohl řádně užít Podlesí jak se sluší a patří. <br>⌐■_■"

		[[params.tickets.paras]]
			para = "Výše vstupného je dobrovolná a závisí na tobě jak moc nás budeš chtít podpořit. Neboj, vše dáváme do podlesí a ani koruna nepadne nazmar. Do morku kosti se snažíme využít každou&nbsp;peny, na maximální kalbu."

		[[params.tickets.paras]]
			para = "Doporučená výše vstupného na 3 dny je <strong>250kč</strong>. Samozdřejmně se na tebe nebudeme zlobit, když nám nějaký ten fufník přihodíš navíc. Pokud nám přispěješ částkou nad 300kč, můžeš se u&nbsp;vstupu těšit na uvítací párt balíček který ti jistě přijde vhod ;)"
